version: '3.8'

services:
  # Apache and PHP service
  web:
    build: .
    container_name: BAI-Proj-PHP-container
    ports:
      - "8899:80"
    volumes:
      - ./www:/var/www/html
      - ./conf/apache2.conf:/etc/apache2/apache2.conf
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - my-network

  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: BAI-Proj-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RbiELHi8
      MYSQL_DATABASE: bai
      MYSQL_USER: baiuser
      MYSQL_PASSWORD: baipassword
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my-network
# Define networks
networks:
  my-network: